### ISSUE TITLE
Ana sayfada bulunan kritik güncelleme yazısı

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#100]
Çeviri sitesinde kritik güncelleme yazısı orijinal halinde kalmış @ayhankuru bizim depoda güncel çeviriler yok onuda pull request atalım istersen.

**Comment by c0b41** [comment]
onu bende farkettim ama template.json'da bulunmuyor, sanırım build ederken ekliyorlar 
https://github.com/nodejs/iojs.org/blob/master/content/en/template.json

**Comment by KiPSOFT-zz** [comment]
ok o zaman kapatıyorum.
