### ISSUE TITLE
nodejstr.com sitesi hakkında

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#108]
Merhaba arkadaşlar konuyu burda tartışalım çünkü Türkiye topluluğundan destek almadıkça bunu kaldırmayacaklarını söylediler. Şimdi orada geçen terim topluluk sonuçta nodejstr bir topluluk üyesi fakat bu topluluğun resmi bir sitesi değil. nodejs.org üzerinde geçen terim topluluk siteleri. Bence topluluğun bu işte para kazanmayacağı diye bir şey söz konusu değil. Bunlar benim görüşüm. Tartışarak uygun bir çözüm bulunabilinir düşüncesindeyim.

**Comment by behcet** [comment]
Eğer Türkiye ile alakalı ya da Türkçe bir topluluk sitesi değilse o listede yer almaması gerekiyor.

**Comment by KiPSOFT-zz** [comment]
node.js topluluğunda yer alan bir site diye düşünüyorum ben.

**Comment by behcet** [comment]
"Eğitim ve danışmanlık" linkinin topluluk ile ilgisi nedir ? _iletisim@nodejstr.com_ adresine giden mailleri kim cevaplıyor ?

**Comment by c0b41** [comment]
Türkçe bir topluluk sitesi değil, daha çok nodejs yazıları bulunan blog. ben kaldırılmasından yanayım.Topluluk olması için bu internet sitesinde kullanıcıların olması gerekli, mail listeleri ne bileyim bu topluluğun yapmış olduğu etkinlikler olmalı.Aynı şekilde topluluklar para karşılığı hizmet vermezler, bu kişisel bi konudur o yüzden olmaması gerek, sadece olur tarafı olan kısım domain isminin oluş tarafı.  nodejs/nodejs.org#158 issue'da olduğu gibi konuşmalarda işin profesyonel şekilde devam ettirilmediğini gösteriyor.

**Comment by KiPSOFT-zz** [comment]
joyent sevabına çalışan bir firma mı arkadaşlar ? topluluk o mail listeleri, bloglar ve kullanıcıların tümünü kapsıyor. sonuçta bu işte para kazansalar da yazılı kaynak paylaşıyorlar.

**Comment by c0b41** [comment]
joyent makaleden mi para kazanıyor adamlar sunucu şirketi bunun toplulukla ne alakası var, nodejstr'de yöneticilik yapan adam gitsin kendi profilinden hizmet versin.

**Comment by KiPSOFT-zz** [comment]
"Node.js is a trademark of Joyent, Inc." kim makaleden para kazanıyormuş ben çok yanlış anlamışım konuyu, konu sitenin bir tarafında eğitim ve danışmanlık bilgilerinin yazılması değil mi ? bu nodejs markasını joyent'in tescil ettirmesi ile aynı şey. sonuçta platform açık kaynak mı evet. bu da aynı sonuçta bir makale yayınlayıp sana sunuyorlar mı sunuyorlart e o zaman. sapla samanı karıştırıp kendi kendimizi baltalamaktan başka bir şey yapmıyoruz. neyse zaten kaldırıldığından konuşulacak bir şey kalmadı.
