### ISSUE TITLE
new.nodejs.org sitesi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#118]
4.0 sürümü ile beraber io.js/node.js birleşmesi tamamlanacak. Yeni websitesini domain'e derleyip yüklemişler. Bununla ilgili bir yerelleştirme dökümanı olmamasına rağmen depoyu fork edip bakabiliriz.

**Comment by 0zguner** [comment]
Benim için uygundur.

**Comment by KiPSOFT-zz** [comment]
locale/en klasörü çoğaltılıp Türkçe çevirisi yapılabilir https://github.com/nodejs/new.nodejs.org

**Comment by c0b41** [comment]
Dizin eklendi.
