### ISSUE TITLE
spread operatörü

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#119]
Merhaba;

Yeni ES6 ile beraber bu operatör geldi 3.0 ile beraber io.js'de herhangi bir bayrağa gereksinim duymadan çalışabiliyor, yaptığı işlem fonksiyonun parametrelerinin sınırsız veya sonsuz olduğu anlamına geliyor birden çok parametre belirtilebiliyor. Bunun için diğer dillerde Türkçe karşılığın ne olduğunu bilemiyorum bu sebeple sonsuzluk operatörü gibi bir çeviri yaptım fakat saçma olabilir. Orjinal şeklinde de bırakılabilinir. TERIMLERSOZLUGU'ne ekledim. Fikirlerinizi bekliyorum.

**Comment by 0zguner** [comment]
sonsuzluk ile alakasını tam anlamadım https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Operators/Spread_operator

bence genişletme/yayma operatörü daha iyi olacaktır çeviri için.

**Comment by KiPSOFT-zz** [comment]
İşlevin kendisiyle genişleme/yayma'yı bağdaştıramadım o yüzden öyle bir terim kullandım.

**Comment by 0zguner** [comment]
benim anladığım şey: fonksiyonların aldığı parametrelerin genişletilebiliyor olması... benim fikrim... spread'in kelime anlamları genişleme/genişletme/yayma/yayılma bence buradan yola çıkılabilir. Ayrıca bence çevirilerde kelimlerin sıfat, zamir, zarf , fiil ve isim gibi hallerine dikkat etmemiz lazım. Spread fiil hali gibi geldi bana dolayısıyla çeviri de fiil olmalı.

**Comment by KiPSOFT-zz** [comment]
parametreleri genişletmekten ziyade parametreleri esnek hale getiriyor. fiil halini kullanırsak yine bana anlamsız geliyor ama dediğiniz gibi direk düşünürsek sizin dediğiniz gibi.

**Comment by c0b41** [comment]
Şuan için olduğu gibi kalmadı, daha sonra belki

**Comment by 0zguner** [comment]
function topla(a, b) {
    return a + b;
}

let sayi_dizisi = [10, 11];

console.log(topla(...sayi_dizisi));

Şu olayın neresinde sonsuzluk var anlamadım. Böyle kalmamalı.

**Comment by c0b41** [comment]
@mzgnr ne işe yaradığını biliyorum bunu tartışmak için erken diyorum

**Comment by KiPSOFT-zz** [comment]
@mzgnr değiştirilebilir benim için illa öyle olsun deseydim konuyu açmazdım. düşününce diğer alternatiflerden yayma daha uygun geliyor?

**Comment by behcet** [comment]
Yayma ya da dağıtma daha uygun bir çeviri olur diye düşünüyorum.
