### ISSUE TITLE
iojs - > nodejs

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#120]
4 sürümle beraber sanırım birleşme olacak ama son 1 aydır herşey nodejs derneğine geçmiş durumda, diğer bütün iojs takımları zaten çoktan çeviriyi bırakmış durumda.İojs haftalık bültenleride artık sadece nodejs org altında paylaşılmaya devam ediyor.

Benim sorum çevirilere devam edilmelimi?

bu konuda ne düşünüyorsunuz

**Comment by KiPSOFT-zz** [comment]
Şu anda 4.0 release oldu ve artık io.js diye bir şey artık resmen yok. node.js 4.0 sürümü var bülten yayınlama devam etse bile artık diğer dillere uygun bir website yok şu anda.

**Comment by 0zguner** [comment]
website reposunda locale klasörü mevcut. bence oradan çevirme yapılacak.
