### ISSUE TITLE
medium.com adresinin nodejs_tr olarak değiştirilmesi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#123]
medium.com adresinin nodejs_tr olarak değiştirilmesi

**Comment by c0b41** [comment]
Twitter hesabiyla giris yapilip  degistirilebilir

**Comment by c0b41** [comment]
Medium güncellendi, yeni mail için onaylama gönderdi hocam halledersin.

**Comment by KiPSOFT-zz** [comment]
ok değişti. adresi de https://medium.com/@nodejs_tr
