### ISSUE TITLE
Çeviri

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#129]
Node.js'in artık lokalleşmeyle ilgili bir çalışması yok. Diğer gruplarda da iş durmuş durumda. Ben elimden geldiğince Twitter hesabını aktif tutmaya çalışıyorum ama düşüncem en azından medium hesabını da bilgi amaçlı olarak güncel tutalım. Twitter ve medium konusunda yardımcı olacak arkadaşlar varsa güzel olur.

**Comment by 0zguner** [comment]
Lokalleşmenin durdurulduğunu belirten issue'yu buraya referans olarak ekleyebilir misin ? Bazı takımlar lokalleştirme çalışmalarına devam ediyor.

**Comment by KiPSOFT-zz** [comment]
Ben çalışma olarak bakıyorum. Hangileri devam ediyor ilk zamanlarda çok aktif olan kore ve ispanya takımlarında bir değişiklik görmedim. Belki atlamışımdır.

**Comment by KiPSOFT-zz** [comment]
Misal ana websiteye eklenen kore takımının sayfasına bakabiliriz; https://nodejs.org/ko/ ana sayfa dışında herhangi bir ekran çalışmıyor.

**Comment by 0zguner** [comment]
En azında biz de ana sayfayı çevirebiliriz.

**Comment by KiPSOFT-zz** [comment]
Olur tabi ki de, onun yerine enerjimizi topluluğu Türkçe bilgiyle aydınlatmak artık daha mantıklı geliyor. Web sitesi Türkçe olsa bile kaynak olmadan kaybolmak mümkün. Web sayfasını çevirmeyelim demiyorum. Yanlış anlaşılmasın.

**Comment by 0zguner** [comment]
Web sayfasını çevirme işini ben üstlenebilirim. Twitter hesabı galiba zaten sende ? Böyle bir paylaşım yapabiliriz.
