### ISSUE TITLE
Güncel site çeviri

### ISSUE THREAD

**Issue by enverarslan** [iojs/iojs-tr#133]
Merhaba. Mevcut sitenin çevirisi için kimler müsait?

https://github.com/nodejs/nodejs.org/blob/master/TRANSLATION.md

**Comment by gokaygurcan** [comment]
#130

**Comment by enverarslan** [comment]
Aradan iki senelik bir sessizlik dönemi geçmiş. Aktifliği buradan başlatırsak iyi olur gibi.


https://github.com/nodejs/nodejs-tr/commit/2d966bc41bd08fc45d599ec9aea03820befb7b70 ile çevirilecek dosyaları ekledim repoya fakat PR için nasıl bir yol izlemeliyiz bunu konuşmamız gerek. Çünkü mevcut repo sitenin forku değil.

**Comment by 0zguner** [comment]
Temiz bi başlangıç yapmaktan yanayım

**Comment by enverarslan** [comment]
@gokaygurcan @mzgnr bu konuyu gitter'da mı tartışsak?

**Comment by enverarslan** [comment]
https://github.com/nodejs/nodejs.org/pull/2777
