### ISSUE TITLE
20.02.2015 Haftalık Bülten

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#15]
Haftalık bülten yayınlandı. Orjinal halini attım ve çeviriyi yaptım. İnceleyip uygun görürseniz yayınlayalım.

**Comment by c0b41** [comment]
Uygundur yayınlayalım :)

**Comment by c0b41** [comment]
Düzenleme yaptım ve medium üzerinde paylaştım, issue kapatıyorum
