### ISSUE TITLE
Terimler Sözlüğü

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#19]
Terimler sözlüğü hakkında bazı şeyleri belirlememiz gerekiyor bu issue bunun için açtım, öncelikle bir çok kelime eklendi node dışında kelimelerde var sizce node dışında kelimelerde olmalımı yoksa sadece node ve javascript üzerine olan kelimelerimi eklemeliyiz?

Kendi görüşüm her kelimeye ekleyelim, çünkü haftalık bültenler ve sürüm değişikliklerinde bazı kelimeler geçiyor ben işe yarayacağını düşünüyorum.Fikirlere görede sözlüğü düzenleriz.Bunun dışında md dosyası içerisine yorum yapmak pek mantıklı gelmiyor, kelimenin eklendiği commit  üzerinden bence fikirlerimizi paylaşalım 

cc @KiPSOFT @enverarslan @behcet-li

**Comment by enverarslan** [comment]
Olabildiğince yazılımla alakalı kelimeler bulunsun. Fazlalık zarar vermez bize. Hem sadece io.js için değil genel bir sözlük olur. Her ne kadar her kelime tam anlamı ile çevrilemese de.

Şu an fork edip düzenleyecek durumda değilim fakat bazı kelimeler için önerilerde bulunayım.

iterator: yineleyici,
reject: reddetmek,
resolve: çözümlemek, halletmek. 
stream: akış,
destructor: imha eden.

Ayrıca kelimelerin çoğulları yazılmasın; promises değil promise, generators değil generator.

**Comment by KiPSOFT-zz** [comment]
Bütün kelimer eklenebilir bence sakıncası yok. @enverarslan dediği gibi çoğullar yerine tekil durumları yazalım.

**Comment by behcet** [comment]
Az önce burada "issueları self assign ederiz" gibi saçma sapan bir cümle kurdum. Bu şekilde yazılmış Türkçe bir dökümanı okumak yerine orjinalini tercih ederim. API dökümanlarını çevirirken akıcı ve sade bir dil kullanılması taraftarıyım. Bu yüzden terimler sözlüğüne Node/IO.js bağlamının dışında da sıkça kullanılan -özellikle bilgisayar bilimleri kapsamındaki- her kelimeyi eklemeliyiz.

**Comment by KiPSOFT-zz** [comment]
Bence de illa düz mantıkla çevirilecek diye birşey yok kendimizin anlayacağı şekilde çevirmemiz lazım.
