### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by 0zguner** [iojs/iojs-tr#22]
bugün io.js Türkiye için bir logoyu ben hazırlayabilirim başka talip yoksa :smiley:

**Comment by c0b41** [comment]
Logo çok lazım değil ama, medium yazılarında veya herhangi bir konuda yazı yazarken görsel olarak kullanabiliriz

**Comment by KiPSOFT-zz** [comment]
io.js takımında böyle bir karar yok @ayhankuru belirttiği gibi başka yerlerde kullanılabilir.

**Comment by 0zguner** [comment]
İspanyollar güzel bir logo yapmışlar.

**Comment by KiPSOFT-zz** [comment]
https://iojs.org/es/ bu adreste mi ?

**Comment by 0zguner** [comment]
https://github.com/iojs/iojs-es/tree/master/public/images burada gördüm.

**Comment by KiPSOFT-zz** [comment]
Böyle bir logo bence mantıklı.

**Comment by 0zguner** [comment]
Bu arada ben şimdi bir duvar kağıdı yaptım. iojs in fontunu öğrendiğim zaman hem wallpaper hem logoyu paylaşacağım :)

**Comment by c0b41** [comment]
yazılarda kullanılabilir, websitesinde düşünmüyorum :) beklemediyim klasör olarak gönderebilirsin

**Comment by c0b41** [comment]
@mustafaozguner ilerleme varmı? yoksa issue kapatalım mı?

**Comment by 0zguner** [comment]
tamamen unutmuşum. haftasonu ekleyeceğim :)
