### ISSUE TITLE
Ekibe Katılım

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#25]
https://github.com/iojs/website/issues/125 issue'da katılmak isteyen arkadaşlar burdan kendilerini belirtirlerse kendilerine collaborator yetkileri verebilirim, iojs organizasyonuna şuan için alamıyorum

**Comment by 0zguner** [comment]
Belirttiğin linkten belirteceğiz değil mi ?

**Comment by c0b41** [comment]
ordan belirtilenler takip edilmiyor bu issuedan belirtinsin, anlamında açtım bunu

**Comment by c0b41** [comment]
ordan ekleme oluyor kapatıyorum burayı.
