### ISSUE TITLE
iojs.tc uzantısı alınmalı mı ?

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#26]
Arkadaşlar norveç takımı iojs.no diye bir uzantı alıp yönlendirmiş. io.js sitesinde halen bir dil seçme bölümü yok. Bununla ilgili gelecek website grup toplantısında bir karar alınacağı yazılmış. https://github.com/iojs/website/issues/136  Şurada bir çeviri politikası var; https://github.com/iojs/website/blob/master/TRANSLATION.md Fakat anladığım kadarıyla kesin bir kanı yok tayvan ve çin websiteleri almış başlarını gitmiş. Bu konuda ne düşünüyorsunuz ?

**Comment by 0zguner** [comment]
.tc Türkiye Cumhuriyeti için özel bir alan adı değil diye biliyorum.

**Comment by KiPSOFT-zz** [comment]
Evet özel bir alan değil amacım ayrı bir uzantı alınıp alınmayacağı konusu aslında.

**Comment by c0b41** [comment]
norveçliler yapmış ama bana gereksiz geldi iojs girildiğinde otomatik olarak /tr/index.html şeklinde yönlendiriliyor olucak. Kendi kafamıza göre websitesini yönetirsek kopukluklar olacak. Aynı şekilde bir kaç grupta ghost blogları açmışlar çok gereksiz. Biz @enverarslan 'la iojs hakkında turkçe blog yazmayı düşünüyoruz yazılarda medium üzerinde olucak sizde yazabilirsiniz. Medium hesabımızda da bunlar için kategoriler açıldı https://medium.com/@iojs_tr/publications

**Comment by 0zguner** [comment]
Şimdi ben bir Node.js projesi yapıyorum. Startup olma durumu yok gerçi ama bitirdikten sonra io.js'e geçireceğim ve expressjs kullanmadan sıfırdan yazacağım gibi görünüyor. Aralarda dinlenirken logo ve çeviri işlerini hallediyorum. ama bence bir kaç gün içerisinde bitirmemiz lazım. İspanyolların sayfası açılmış bile.

**Comment by c0b41** [comment]
Ben yarın geceye faq sayfasını tamamlamış olurum, es6 sayfası geldiğinde kendi forkum üzerinden birleştirip website reposuna ileticem :) bu arada direk iojs kullanabilirsin daha stabil :) express yerinede koa'a göz at istersen :)

**Comment by 0zguner** [comment]
projeyi release edeyim önce, sonra iojs'e geçeceğim :)

**Comment by KiPSOFT-zz** [comment]
Bence total.js ;)

**Comment by c0b41** [comment]
@KiPSOFT ayrı bir domain olabilir ama tc çok çirkin bana göre iojsturkiye.com gibi birşey olabilir

**Comment by KiPSOFT-zz** [comment]
Ben norveçlileri düşünürek önerdim. Eğer dediğin gibi io.js'te otomatik dil ayrımı olacaksa bir sorun yok bence.

**Comment by 0zguner** [comment]
zaten io.js'in bir nebze çıkış sebebi joynet'in javascript topluluğundan kopması. Bence norveçliler yanlış yapmışlar.

**Comment by KiPSOFT-zz** [comment]
Şu an için gerek olmadığı için kapatıyorum.
