### ISSUE TITLE
açıklama değişikliği

### ISSUE THREAD

**Issue by 0zguner** [iojs/iojs-tr#27]
bu reponun açıklamasının "io.js - Türkçeleştirme takımı" 'ndan " Turkish Localization " değiştirilmesi daha güzel duracak gibi. Çoğunluk açıklamalarını bu şekilde yapmış.

**Comment by KiPSOFT-zz** [comment]
Ukrayna, İtalya, İspanyol, Çin, Tayvan, Japonya gibi bir çok takımda yerel dille yazılmış açıklamalar.

**Comment by c0b41** [comment]
Repo yabancılara hitap etmediği için gerekli görmüyorum, diğer arkadaşlar yorumlarını yaptıktan sonra duruma göre bakarız

**Comment by enverarslan** [comment]
Türkçe topluluk olmasının anlamı kalmaz o zaman.

**Comment by c0b41** [comment]
issue için yeterli zaman olduğunu düşünüyorum, aynı kalmasında hemfikirsek issue kapatıcam

**Comment by 0zguner** [comment]
evet hem fikiriz. kapatabiliriz
