### ISSUE TITLE
Api Çevirisi Hakkında

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#31]
Öncelikle https://github.com/iojs/website/issues/211 bu issueda api dökümanı için build tool hazırlandığı söylenmiş, bunun dışında website reposuna ne zaman taşınacağı belli değilmiş.

Rus çeviri grubu api dökümanını ve nodeun build tool'unu kendi repoları koymuşlar.Bizde bunu kullanıp sizce çeviriye başlayalım mı? daha sonrasında geliştirilcek build tool ile render edilebileceğini düşünüyorum

Bunların dışında api dökümanı bölümlendirmesini nasıl yapalım fikirlerini bekliyorum 

/cc @KiPSOFT @behcet-li  @enverarslan @hwclass @mustafaozguner

**Comment by 0zguner** [comment]
büyük ihtimalle build tool ile render edecekler. Localization olayını ancak böyle birşey ile handle edebilirler diye düşünüyorum. Benim için hiç fark etmez. önce ikişerli bir dağılım olsun sonra bitiren iki tane daha alsın. Ancak bir yerde bunu takip etmemiz lazım. Toptan bir paylaşım yapıp yetiştirememezlik gibi bir durum olmasın diyorum.

**Comment by KiPSOFT-zz** [comment]
belirli başlı apileri içeriğin önceliği sırasına göre dizelim. örneğin alfabetik sırayla yaparsak errors veya file system yerine c/c+ addons sayfasını çevirecez. bunun yerine öncelik sırası belirleyelim. @mustafaozguner  dediği gibi tümünü bölümlemek yerine bitince yenisine başlamalı. arada pull request'le bazılarını atarız. tamamını bir anda çevirmemizi beklemiyorlar herhalde.

**Comment by c0b41** [comment]
Bir konuyu alalım onu çevirip diğerine geçelim diyorsunuz yani

**Comment by 0zguner** [comment]
@ayhankuru  senin yaptığın bir tablo vardı yanına tik atabiliyorduk. onun gibi birşey yapalım alanınanların yanında tik olsun bittikçe onu güncelleriz ?

**Comment by c0b41** [comment]
@mustafaozguner #5'te mevcut

**Comment by 0zguner** [comment]
Çok iyi. Ben ubuntu 15.04 e geçiş yaptım. Bilgisayarı biraz toparlamam zaman alabilir. Okula da uğramam lazım arada sırada :D projemi de yetiştirmeye çalışıyorum. Ne zaman başlayacağız çevirmeye ?

**Comment by behcet** [comment]
API dökümanlarında her kısım için bir issue açıp pull request atabiliriz. Herhangi bir bölüm üzerinde çalışmaya başlayacaklar katılımcılar issue'u üstlerine alıp çalışmaya başlarlarsa bir karışıklık yaşanmaz diye düşünüyorum.

**Comment by KiPSOFT-zz** [comment]
@behcet-li  dediğine katılıyorum çevirmeye başladığımın sayfalar hakkında bir bildirim açalım ve üstümüze alalım, başka biri devam ederse o kişi üstüne alır.

**Comment by c0b41** [comment]
@KiPSOFT bencede baya mantıklı çeviri kısmında görülen hatalar düzeltmelerde o issue'ya referans olarak gösterilerek merge edilir, daha kontrollü olur

**Comment by c0b41** [comment]
konuşmalar konusunda hemfikiriz heralde, kapatıyorum.
