### ISSUE TITLE
iojs nasıl türk developer'lara duyurabiliriz

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#32]
Bu issue'da fikirlerinizi almak için açıyorum, nodejs ile geliştirme yapan türk developerlarını nasıl iojs konusunad haberdar edebiliriz

**Comment by 0zguner** [comment]
Belli başlı frameworkler io.js üzerinde stabil çalışmaya başlamadığı sürecek türk developerları çekebileceğimizi sanmıyorum. En azından express.js veya alternatifi boy gösterirse tutoriallarla ilgi çekebiliriz diye düşünüyorum.

**Comment by KiPSOFT-zz** [comment]
bence tanışma toplantıları düzenlemeli (meetup) zaten bununla ilgili bir issue vardı.

**Comment by 0zguner** [comment]
evet böyle birşey de yapılabilir.

**Comment by c0b41** [comment]
Meetup için bir organizasyon, ruby turkiye, python istanbul gibi oluşumlar oluşturmak gerekli.
Nodejs turkiye grubu vardı onla iletişime geçip birşeyler yapmak gerekli

**Comment by 0zguner** [comment]
evet node.js türkiye grubuna üyeyim ben galiba. bence bizim milleti node.js'ten koparmamız biraz zor olacak :D

**Comment by c0b41** [comment]
Nodejs'den kopma gibi bi durum yok zaten, bi ara sohbet edersek durumları anlatıcam

**Comment by KiPSOFT-zz** [comment]
Twitter'dan meetup lar için duyuru geçelim mi ?

**Comment by c0b41** [comment]
Güzel olur, nodejs turkiye ile iletisime gecip meetup yapabiliriz.
