### ISSUE TITLE
İletişim kanalı

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#33]
İletişimde kalmak için kullanışlı bi yer gerekli, gitter fazlasıyla sade slack çok hoş, yada irc de bir kanal oluşturabiliriz önerilere açığım

**Comment by 0zguner** [comment]
ben gitter a pek ısınamadım. ama çoğunluk ne derse ona uyarım.

**Comment by enverarslan** [comment]
slack olabilir ama herkese açık olması lazım. slackta davet gerekli. irc kanalı daha makul.

**Comment by behcet** [comment]
Gitter'i offline mesajları gösterdiği için IRC kanalına tercih ediyorum. [Hipchat](https://www.hipchat.com/) iyi bir alternatif olabilir

**Comment by c0b41** [comment]
bende irc'i düşünmeye başladım, bi ara toplu halde sohbet edelim

**Comment by c0b41** [comment]
irc kanalı açmayı bile varsa bi kanal açarak orda genel olarak olan bitenler hakkında muhabbet edelim?

**Comment by 0zguner** [comment]
irc kanalını ben hallederim.

**Comment by KiPSOFT-zz** [comment]
freenode üzerinde açabilirsiniz.

**Comment by c0b41** [comment]
@KiPSOFT @mustafaozguner ikinizden biri açarsa ordan konuşalım, freenode la birşeyle okudum ama baya karmaşık geldi size bırakıyorum :smile:

**Comment by KiPSOFT-zz** [comment]
http://webchat.freenode.net/?channels=io.js-tr
