### ISSUE TITLE
Roadmap çeviriye hazır

### ISSUE THREAD

**Issue by 0zguner** [iojs/iojs-tr#35]
https://github.com/iojs/roadmap/issues/18 buradan ayrıntıları okuyabilirsiniz.

**Comment by c0b41** [comment]
Nasıl yapalım bu repoya koyarak mı çevirelim? kim pull request olarak taşır oraya

**Comment by 0zguner** [comment]
Repoya koyarak çevirelim. Benim boş vaktim var ben hallederim

**Comment by 0zguner** [comment]
Bu arada sadece html dosyasını çevirin yeter demişler.

**Comment by c0b41** [comment]
Tamam sen taşı, pull olarak tamamlandığındada oraya taşırsın

**Comment by KiPSOFT-zz** [comment]
Bu arada ne kadar saçma bir roadmap sitesidir bu ?

**Comment by 0zguner** [comment]
@ayhankuru  işte ben o dediğini nasıl yaparım bilmiyorum :D

**Comment by c0b41** [comment]
@mustafaozguner  Buraya ekliyorum birazdan çevirildikten sonra, ben gönderirim :)

**Comment by KiPSOFT-zz** [comment]
Bu işi kapatıyorum arkadaşlar. Çeviri için ayrı bir iş açıyorum.
