### ISSUE TITLE
io.js Türkiye Tanışma Toplantıları

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#37]
io.js Türkiye çeviri takımı olarak io.js tanışma toplantıları düzenlemeyi düşünüyoruz. Katılım gösterecek arkadaşlar bu bildirim altına fikirlerini belirtebilir ve her şehir için organize olabiliriz.

**Comment by bonesoul** [comment]
ankara için olursa katılmak isterim

**Comment by hwclass** [comment]
İstanbul'dakine katılabilir, organizasyon işinde yeralabilirim.

**Comment by KiPSOFT-zz** [comment]
Bende izmir için yapılacak organizasyonlarda yer alırım ve organize edebilirim. İstanbul için @hwclass bir gün belirleyin isterseniz duyuralım geri dönüşlere göre karar verirsiniz. İstanbul için en azından 3, 4 kişi çıkacaktır. Diğer iller için daha yaygın bir kitle olursa ona göre organize olalım. Ayrıca bu meetuplar için io.js resmi twitter hesabından retweet etmesini isteyebiliriz @ayhankuru ne dersiniz ?

**Comment by c0b41** [comment]
Yaz aylarında olursa istanbul ve ankarada küçük buluşmalar düzenleyerek başlayabiliriz @KiPSOFT olabilir ama ben bile müsait değilim yaz aylarını beklemekten yanayım
