### ISSUE TITLE
Website çevirisi

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#4]
https://github.com/iojs/iojs-tr/tree/master/website/tr
- [x] index.html
- [x] faq.html
- [x] es6.html

Çeviri alanı güncellendi. Artık iojstr reposu üzerinden çevirebiliriz, çeviri tamamlandığında kendi website fork'um üzerinden website grubuna ileteceğim.

cc @KiPSOFT

**Comment by KiPSOFT-zz** [comment]
Onlar bizden bu çeviri nasıl alacaklarıyla ilgili bir açıklama geçtiler mi ?

**Comment by KiPSOFT-zz** [comment]
Baktığımda herhangi bir açıklama mevcut değil. İkisi de olabilir her ikisi de aynı sonuçta.

**Comment by KiPSOFT-zz** [comment]
Bu arada api dökümantasyon ile ayrıntılı bir bilgi bulamadım. Öncelik websitesi sanırım. Twitter ve medium.com bilgilerini mailine gönderiyorum.

**Comment by c0b41** [comment]
Bilgi yok bende diğer çeviri repolarını takip ediyorum çin repolarından biri static site branch'ına iletmiş website çevirisini, ama gulp ile yapılmış hazır hali varmış otomatik build eden bunu kullanmak daha mantıklı.

**Comment by c0b41** [comment]
Api dökümanı ile ilgili hiçbir bilgi yok şuan eve sadece issue olarak açtım, website çevirisi ile ilgili olaylar bilgilendirme yapılır büyük ihtimalle bi karışıklık var sanırım orada

**Comment by KiPSOFT-zz** [comment]
https://gitter.im/iojs/iojs-tr

**Comment by c0b41** [comment]
https://github.com/ayhankuru/website/tree/website_tr

Çeviriye başlıyorum :)

**Comment by KiPSOFT-zz** [comment]
bende es6'yı çevricem ama hafta sonuna sarkabilir.

**Comment by KiPSOFT-zz** [comment]
ben es6'yı bu hafta bitirmeye çalışacam fakat bu website çevirisini hızlandırmamız lazım çoğu dilde bitirmişler.

**Comment by c0b41** [comment]
Evet Bende gördüm, haftasonuna tamamlıyacağım anasayfayı çevirmiştim zaten :+1:

**Comment by KiPSOFT-zz** [comment]
es6 dökümanını çevirdim. yalnız "there might be some edge cases left to discover" şu metini çeviremedim arkadaşlar düzenlemelerinizi bekliyorum.

**Comment by 0zguner** [comment]
aslında aklıma ilk gelen çeviri " kıyıda köşede kalmış keşfedilmeyi bekleyen hususlar olabilir."

**Comment by 0zguner** [comment]
Tabi yanlış çeviri :D "edge case" iki anlama geliyor. birincisi maksimum veya minimum durumlarda meydana gelen hata. ikinci olarak, algoritmaların, fonksiyonların veya metodların sınır koşullarını test eden bir "unit test" anlamına gelmektedir.

**Comment by KiPSOFT-zz** [comment]
@mustafaozguner bununla ilgili düzenlemeyi yaparsan yayınlayalım. birde genel olarak bir kontrol edin isterseniz yanlışlarım olabilir.

**Comment by c0b41** [comment]
Bir iki kelime çevirdim ama, bugün tamamlayamacağım sanırım işlerim var, geri kalan kısımları tamamlayan olursa gece hepsini toplayıp ben ileticem

**Comment by 0zguner** [comment]
Bugün halledeceğim mola verdiğimde.

**Comment by c0b41** [comment]
Site güncellendi https://iojs.org/tr/index.html

**Comment by KiPSOFT-zz** [comment]
Otomatik yönlendirme de sorun var. Tweet atalım olmadı.

**Comment by c0b41** [comment]
konu hakkında çalışıyorlar https://github.com/iojs/website/issues/235
