### ISSUE TITLE
27.02.2015 Haftalık Bülten Çevirisi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#43]
27.02.2015 Haftalık Bülten Çevirisi

**Comment by c0b41** [comment]
Akşam üzeri birçok kısmını çevireceğim

**Comment by KiPSOFT-zz** [comment]
@ayhankuru bir değişiklik yaptın mı ? İstersen bende yardım edeyim ?

**Comment by c0b41** [comment]
@KiPSOFT uzun süredir çevireye bakmıyorum belki haftasonu

**Comment by KiPSOFT-zz** [comment]
@ayhankuru ben tamamladım bir bakarsan yayınlayalım.

**Comment by c0b41** [comment]
@KiPSOFT yayınlayalım, roadmap'a bakıyorum o zaman

**Comment by KiPSOFT-zz** [comment]
@ayhankuru yayınlamışsın sen sağol. Roadmap için bir iş açalım.
