### ISSUE TITLE
Nodejs vakfı ile uzlaşma

### ISSUE THREAD

**Issue by 0zguner** [iojs/iojs-tr#44]
https://github.com/iojs/io.js/issues/978 Buradan anladığım üzere yakın bir zamanda uzlaşma olması muhtemel. Ancak Node.Js topluluğu böyle bir ayrılık olmasından dolayı zaten çok rahatsız hissediyormuş ve onların github sayfasında açılan issue kapatılmış. Sizlerin de fikirlerinizi bekliyorum.

**Comment by c0b41** [comment]
@mustafaozguner Başlık hatalı düzeltirsin onu.Joyentle uzlaşmak değilde nodejs vakfı ve iojs'nin tekrar node ile birleşmesi üzerine fikir alışverişi issue açıldığından beri takip ediyorum sorunlardan biri birleşme olursa v12 için konuşulan sıkıntılar çıkabileceği aynı şekilde dökümanlarda sıkıntılı, konu hakkında birçok kişi fikrini söylemiş genel olarak herkes birleşerek topluluğun güçlenmesi yönünde.Ama joyent bu fikri pek sıcak bakmıyor sanırım şuan için, issue'daki diğer konuda nodejs vakfı kurulduktan sonra orda olacak teknik komite üyeleri ile ilgili. joyent'deki issue nın kapatılması yanlış bi alana açılmış olması node'un ana reposuna taşında daha sonra ama tjfontaine'ın konu hakkında yorumunu okursanız ben bu adamlardan node'un geleceği ile pek umutlu değilim.Node vakfı hiç bi işe yaramazsa elimizde sadece iojs şeklinde kalacak.

**Comment by bonesoul** [comment]
konuyla ilgili bir miktar tartısmada https://github.com/iojs/io.js/issues/1336'da yürüdü. detaylı inceleyememiş olsamda ben sahsen io.js'i o veya bu şekilde takip etmeyi düşünmekteyim.

**Comment by KiPSOFT-zz** [comment]
Bu konuyu kapatıyorum arkadaşlar artık neredeyse node.js derneğine katılım gerçekleşti.
