### ISSUE TITLE
Roadmap çevirisi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#46]

**Comment by c0b41** [comment]
@KiPSOFT çevirinin artık tamamlanması gerekiyor

**Comment by KiPSOFT-zz** [comment]
halledelim bu aralar işler yoğun pek ilgilenemedim kusura bakma.

**Comment by KiPSOFT-zz** [comment]
Tamamlandı. Yayınlanması lazım. @ayhankuru
