### ISSUE TITLE
06.03.2015 Çevirisi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#47]
Haftalık klasörüne orijinal metin eklendi.

**Comment by KiPSOFT-zz** [comment]
Çeviriyi tamamladım uygun görürseniz yayınlayalım.

**Comment by c0b41** [comment]
@KiPSOFT kontrol ettim , yayınladım. https://twitter.com/iojs_tr/status/574524817753423872
