### ISSUE TITLE
Sosyal medya bannerlarının çevirisi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#48]
Ben twitter hesabına orijinal bannerı ekledim, fakat ilgili bir arkadaş psd dosyasından çeviriyi tamamlayıp atarsa onu yayınlayalım.

https://github.com/iojs/evangelism/tree/master/social-media

**Comment by c0b41** [comment]
![twitter banner](https://cloud.githubusercontent.com/assets/2834954/6545947/9f54ce08-c5a7-11e4-82a2-0ef92a87027e.png)
