### ISSUE TITLE
Api Dökümanı Çevirisi

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#5]
https://iojs.org/api/documentation.html
- [ ] About these Docs
- [ ] Synopsis
- [ ] Assertion Testing
- [ ] Buffer
- [ ] C/C++ Addons
- [ ] Child Processes
- [ ] Cluster
- [ ] Console
- [ ] Crypto
- [ ] Debugger
- [ ] DNS
- [ ] Domain
- [ ] Events
- [ ] File System
- [ ] Globals
- [ ] HTTP
- [ ] HTTPS
- [ ] Modules
- [ ] Net
- [ ] OS
- [ ] Path
- [ ] Process
- [ ] Punycode
- [ ] Query Strings
- [ ] Readline
- [ ] REPL
- [ ] Smalloc
- [ ] Stream
- [ ] String Decoder
- [ ] Timers
- [ ] TLS/SSL
- [ ] TTY
- [ ] UDP/Datagram
- [ ] URL
- [ ] Utilities
- [ ] V8
- [ ] VM
- [ ] ZLIB

**Comment by KiPSOFT-zz** [comment]
https://github.com/iojs/io.js/tree/v1.x/doc/api -  api dökümanları markdown dosyaları

**Comment by 0zguner** [comment]
Bu dökümanlar bizim repoda mı duracak ? Galiba 4 kişiyiz. 4 bölüp çevirme işine başlayabiliriz. Önce Websitesini tamamen bitirelim derim.

**Comment by c0b41** [comment]
Bunlarıda bizim repoya ekleyeyim, bölümlendirmeyi sonra yaparız

**Comment by KiPSOFT-zz** [comment]
Öncelik websitesi bencede. Sanırım bu resmi olmayan bir toplama gibi geldi kesinliği konusunda emin değilim başka bir dilde api görürsek ona göre ilerleyelim ama repoya ekleyelim.

**Comment by c0b41** [comment]
bende onu farkettim website için build tools var sanırım api dökümanları içinde yapılıyor böyle birşey beklemede kalalım bence

**Comment by c0b41** [comment]
Dökümanlarla ilgili bilgi için https://github.com/iojs/website/issues/211
