### ISSUE TITLE
20.03.2015 Haftalık Bülten Çevirisi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#50]
Yazının md sürümü yayınlanınca buraya ekleyeceğim arkadaşlar. @ayhankuru @mustafaozguner @enverarslan @behcet-li

**Comment by c0b41** [comment]
@KiPSOFT Bende ona göz atıyorum, twitter üzerinden linkleri paylaştım, çeviredede yardım edebilirim

**Comment by KiPSOFT-zz** [comment]
@ayhankuru api ile ilgili bir gelişme gördün mü ? ben roadmap'e bu hafta sonu bakacağım.

**Comment by c0b41** [comment]
@KiPSOFT halen aynı durumda bende birşeyler görmedim

**Comment by KiPSOFT-zz** [comment]
@ayhankuru websitesine medium linki eklemişler ispanyolca dilde var örnek olarak. sen düzenleyip pull request atabilirmisin ?

**Comment by KiPSOFT-zz** [comment]
Tamamlandı.
