### ISSUE TITLE
Slack açılmıyor

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#51]
Arkadaşlar slack odasına girebilen var mı ? Ben bir kez giriş yaptım, tekrar giriş yapamıyorum.  @ayhankuru @mustafaozguner @enverarslan @behcet-li

**Comment by c0b41** [comment]
@KiPSOFT heroku uykuya almış, tekrar gelmiş olması gerek ordan invite edersiniz, iletişimde kalmak için orası daha iyi

**Comment by KiPSOFT-zz** [comment]
ben email adresimi yazıyorum invite diyorum herhangi bir mail gelmiyor.

**Comment by c0b41** [comment]
@KiPSOFT slack'a kaydolmuşsun slack'ta varsın şifremi unuttum yaparak dene istersen birde

**Comment by KiPSOFT-zz** [comment]
slack linkinde sadece bana invite ekranı geliyor.

**Comment by c0b41** [comment]
@KiPSOFT join the team dedikten sonra üye olmuş olman gerek, üye olmuşsunda girmişsin bi kere,

iojstr.slack.com adresine girdikten sonra tekrar bilgilerinde giriş yaparsan girersin

**Comment by KiPSOFT-zz** [comment]
Ben ana sayfada ki linke tıklıyorum verdiğin linkte çalışıyor - iojstr.slack.com
