### ISSUE TITLE
10 Şubat dökümanı çevirisi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#7]
Arkadaşlar elimden geldiğince 10 Şubat dökümanını çevirdim. Kontrol ederseniz bir sorun yoksa yayınlayalım.

**Comment by enverarslan** [comment]
ben bir sıkıntı göremedim, eline sağlık.

**Comment by c0b41** [comment]
Hiçbir sorun yok, medium'a gönderdim diğer postuda ben çeviricem issue kapatıyorum, eline sağlık :+1:
