### ISSUE TITLE
io.js'in Tüm plaformlara kurulum dökümanı

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#71]
Arkadaşlar tüm io.js platformlarına kurulumları anlatacak bir döküman hazılrayalım diye düşünüyorum ? Fikrinizi alayım ? Ben ubuntu üstüne kurulumu anlatan bir döküman hazırlayabilirim. Mac OSX, Windows önceliklerimiz olabilir. Medium üstünden yayınlarız.

**Comment by c0b41** [comment]
Medium da iojs hakkinda yazilarda paylasabiliriz, windows ve linux icin bende anlatabilirim

**Comment by KiPSOFT-zz** [comment]
Hangi dağıtım var sende ?

**Comment by c0b41** [comment]
ubuntu var bendede ama dağıtımlar arası farklılıklar olacağını zannetmiyorum

**Comment by KiPSOFT-zz** [comment]
Resmi depolarda yok ubuntu üstünde de ayrı 3. parti bir depoda duruyor. debian tabanlı dağıtımlarda depo ekleme aynı ama diğerlerinde farklılıklar gösterebilir.

**Comment by c0b41** [comment]
distro ve kurulumlar, https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories https://github.com/nodesource/distributions

**Comment by c0b41** [comment]
@KiPSOFT Ben [birşeyler](https://medium.com/@cobaimelan/iojs-ve-nodejs-kurulum-rehberi-ec3213855fa0?source=tw-f975bd1d1f71-1435369709717) yazdım medium'da uygunmudur?

**Comment by KiPSOFT-zz** [comment]
uygundur teşekkürler @ayhankuru bu işi kapatıyorum.
