### ISSUE TITLE
01.05.2015 Haftalık Bülten

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#72]
Çeviriyi tamamladım arkadaşlar sadece takıldığım bir nokta var, "Onboarding another batch of committers" ifadesi bu çeviriyi düzenlersek yayınlayalım. Ayrıca cluster ifadesini olduğu gibi bıraktım. Eğer uygun bir ifade bulursak onuda TERIMLERSOZLUGU dosyasında düzenleyelim.

**Comment by c0b41** [comment]
cluster aynı kalmalı, çeviriyi gönderdim merge edip yayınlayabilirsin

**Comment by KiPSOFT-zz** [comment]
Teşekkürler. Yayınlıyorum.
