### ISSUE TITLE
Tweetlerin çevrilmesi

### ISSUE THREAD

**Issue by KiPSOFT-zz** [iojs/iojs-tr#77]
Arkadaşlar twitter üzerinden atılan tweetlerin çevrilmesi konusunda görüşlerinizi alayım. Ben daha önce bazı tweetleri çevirerek alıntıladım böyle bir durumun daha mantıklı olacağını düşündüm. Bununla ilgili bir eleştiri geldi bu sebeple ortak bir karar almamız gerekebilir.

**Comment by ayhankuru** [comment]
Sonuçta herkes ingilizce anlıyor diye birşey yok kaldı io.js Türkiye olduğu için türkçe yayın yapmalı, pek kulak asmamak gerek ingilizce takip etmek istiyorsa iojs resmi hesabını takip eder.Twetlerde ve terimlerde yanlışlık olduğunu düşünüp böyle birşey diyorsa sonuçta biz ing prof. değiliz o kadar fazla terim varki dogru şekilde aktarmaya çalışıyor

**Comment by c0b41** [comment]
Soruyu yanlış anlamışım alıntı yaparak çevirmek kafa karıştırıcı oluyor bende arkadaşa katılıyorum ama, verdiği tepki anlamsız ve fazla umrumda'da değil io.js tr'nin yayın yapma amacı türkçe olarak io.js ile ilgili haberleri takip edenlere aktarmak, herşeyi türkçeye çevirmemize takıldıysa resmi io.js kanalı takip edebilir. Twitter hesabım gizli olduğunu için mention'u göremedim yoksa direk olarak cevap verirdim bu konuda

**Comment by gokaygurcan** [comment]
Merhaba,
Öncelikle amacımın yaptığınız işi eleştirmek falan olmadığını anlamanızı istiyorum. Yıllardır yazılım sektörü içinde olup, uluslararası bir şirkette Software Developer sıfatıyla aktif şekilde çalışan biri olarak sordum bu soruyu. 
Yaptığımız işin dili İngilizce, kim ne derse desin. Evet, translation ya da localization adı altında gruplar ellerinden geleni yapıyor kendi dillerine bu bilgileri aktarmak için, bu konuda lafım yok; fakat bu, işin temelini değiştirmiyor: eğer yazılım üretecekseniz, İngilizce bilmek zo-run-da-sı-nız. Net. 
Bir süredir aklımdaydı iojs_tr neler yapmış, neler planlıyor diye bakmak, bu sabah vaktim oldu ve birkaç Medium yazısı, roadmap gibi çevirileri okuma fırsatı buldum. Her ne kadar güzel bir fikir gibi dursa da insanları ana dillerinde içeriğe alıştırıp, araştırma ve alternatif yollardan bilgiye erişme anlamında önlerini kestiğinizi düşünüyorum. Twitter'da yazılanları çevirip çevirmemeniz açıkçası beni bağlamıyor bile. İnsanlar dilini anlamadığı, yazdığı şeyi okuyamadığı kişileri takip ediyorsa zaten onların bileceği iş. Anlayabiliyorlarsa gidip kaynağını takip ederler olur biter.

İşin başka bir boyutu, benzer şekilde Türkçe içerik oluşumuna katkıda bulunmak adına Pro Git (v2) kitabının Türkçe çevirileri ile uğraştım bir süre, vakit darlığından bu ara ilgilenemesem de devam etmeyi düşünüyorum. Bunu söylüyorum, çünkü aynı şeyi istediğimizi anlayın istiyorum. Benim sizden farklı olarak istediğim bir tek şey daha var: insanlara anadilinde içerik verip hazıra alıştırmamak. Evet, anlamayacak ve zorlanacaklar. Evet, bıkacak ve bırakacaklar. Ama devamını getirecek kadar kararlı olan bir grup zaten amaçladığı şeye ulaşacaktır. 

Bilgiye erişmek ile hazıra konmak arasındaki farkı lütfen görün. 

@KiPSOFT konuyu buraya taşıdığınız için teşekkürler, 140 karakter bir şeyleri tartışmak için yetersiz olabiliiyor ;)
@ayhankuru tepkiniz neye emin değilim ama yukarıda yazdıklarımı okuyunca belki anlarsınız ne demek istediğimi. Vereceğiniz 'direkt cevap' neyse lütfen çekinmeden söyleyin ayrıca.

**Comment by behcet** [comment]
@gokaygurcan Çevirilerin yazılımcıların önüne geçtiğine inanıyorsan eğer bu görüşünü bizimle değil io.js (node.js) vakfı ile paylaş. Önerin kabul edilirse eğer bütün çevirileri iptal eder, sadece anadilimiz İngilizce ile belgelendirmeye devam ederiz.

**Comment by drlinux** [comment]
Türkçe dökümantasyon fikri çoğu zaman felaketlerle sonuçlanıyor. Zaten Türçe soru sorup cevap alınabilen, düzgün bir şekilde yönetilen IRC, odası e-posta listesi, forum vs gibi ortamlar yaratılması çeviriden, dökümantasyondan çok çok daha faydalı olur.

**Comment by behcet** [comment]
@drlinux Kısıtlı zamanımızla başkalarının hatalarını tekrarlamamıza gerek yok, belgelendirme felaketleri neden yaşanıyor bu konuda bilgi ve deneyimlerini paylaşırsan sevinirim.

**Comment by KiPSOFT-zz** [comment]
Öncelikle görüşleriniz için teşekkürler. Ben konuyu tweetlerin çevrilmesi için açmıştım, fakat başka bir yöne doğru evrilmiş. Şimdi ben kendi açımdan bu çevirilerin Türkiye yazılım sektörüne katkıda bulunacağını düşünüyorum çünkü ilk amacın yazılım sektörü açısından yabancı dil eğitimini özendirmekten ziyade ihtiyaç duyacağı bilgiye kolay ulaşmasını sağlamak olmalı. Sizde takdir edersiniz ki kendi diliyle okunan bir bilgi her zaman bir yabancı dilden daha fazla sağlıklı ve kalıcıdır diye düşünüyorum. Kendi açımdan Türkçe dilinde bir seçeneği olan bir platform, yazılım gördüğümde Türkçe topluluğun olduğunu çıkarıyorum.

Ayrıca bir terminoloji oluşturmak istiyorsak çeviri yapmaktan başka şansımız yok. Bence böyle bir durumda bu konulara daha fazla eğilmemiz gerekmekte. Gerçek anlamda bu ülkede hizmet veren  bu ülkenin firmalarının API dokümantasyonun sadece İngilizce olduğunu bilmek beni üzüyor. (iyzico)
Bu görüşlerim kesinlikle bir yabancı dil öğrenmeye karşı olduğumu uyandırmasın lütfen. Kendi açımdan bu gruba katılırken asıl amacın node.js/io.js API dokümantasyonu olduğunu düşünüyordum fakat maalesef hala bununla ilgili herhangi bir ayrıntılı doküman io.js topluluğu tarafından yayınlanmadı. 

Sonuçta lütfen şunu gözden kaçırmayın bu ülkede yabancı dil bilenlerin oranı %9 - http://utkukaynar.com/2014/07/20/turkiyeistatistik/

**Comment by c0b41** [comment]
@gokaygurcan öncellikle söylediklerine katılıyorum bi programcı birşey öğrenmek istiyorsa öğrenmesi gerektiği dilde bilmeli.Benimde demek istediğim ingilizce olarak takip etmek isteyen takip edebilir bizim amacımız sadece çeviri yapmak değil fikir alışverişinde bulunmak, diğer herkes aynı şekilde katkıda bulunabilir, iojs'nin birinci amacı kominitiye geliştirmek nodejs'deki gibi kopukluklar olmaması için herkes elinden geldiğince cabalıyor, bunlar çeviri ile sınırlı değil api dökümanları vb birçok şey var. Nodejs'i öğrenmeye başladığımda ingilizcem iyi değildi türkçe kaynakda fazla yoktu halen daha yok, biz çevirmezsek biz hakkında birşeyler yazmazsak hiçbir zaman olmayacak bu yüzden insanları aramıza davet etmeliyiz ve hep beraber katkıda bulunmalıyız. @behcet-li dediği gibi bu yönde fikrinde ısrarcıysan  iojs evangelism  reposunda fikrini paylaşabilirsin geri dönüşler alabilirsin.

@gokaygurcan Ben hiç bi zaman türkçe api dökümasyonu göremedim internette siz gördüyseniz şanslısınız, o yuzden felaketlemi gerçekleştiğini bilemiyorum. Öncelikle biz burda birşeyler yaparken kimseden karşılık beklemiyoruz amacımız insanların bilgiye daha rahat ulaşabilmesi api dökümanı yada herhangi bir çeviride çok yanlış yönlendirmelerde bulunduğumuzu düşünüyorsanız siz katkıda bulunabilirsiniz.Diğer bi konuda irc kanalı soru cevap siteleri forumları demişsiniz, iojs den  öncede var olan nodejs turkiye topluluğu var aynı şekilde  https://plus.google.com/communities/102219910544377809997 aynı şekilde bloglarıda bulunmakta. yani soru sorabiliceğiniz kafanıza takılabilecek soruları yanıt bulabileceğiniz alanlar daha öncede vardı.İojs gelirsek 3-4 aylık bir topluluk ve halen gelişmekte iojs ile ilgili mail listemiz,irc kanalımız yok ama kafanıza takılabilecek herhangi bi sorunda slack kanalımızdan bize yöneltebilirsin zevkle cevaplarım.

**Comment by KiPSOFT-zz** [comment]
Herhangi bir geri dönüş olmadığından bu işi kapatıyorum arkadaşlar.
