### ISSUE TITLE
"Build", "İnşa Etmek" değil, "Derlemek" olmalı

### ISSUE THREAD

**Issue by egeozcan** [iojs/iojs-tr#79]
Hem "Compile" hem "Build" aynı kelimeye çevrilemez diyenler olabileceği için PR açmadım.

Evet, "Compile" genellikle bayt veya assembly koduna derleme işlemi için kullanılıyor ve zaten halihazırda da "derlemek" olarak çeviliyor. "Build" de aynı kelimeye çevrilirse anlam kaybı olabilir, bunu anlıyorum.

Bir yandan da sonucun bayt-kodu, assembly ya da küçültülmüş JavaScript olmasının yapılan işi değiştirmediği kanısındayım. Sonuçta bir takım kod, başka bir koda _derleniyor_. "İnşa Etmek" ise bence tamamen inşaat sektörüyle özdeşleşmiş bir kelime. Çevirmek, kurmak veya dönüştürmek (transpile'ın karşılığı?) birer alternatif olabilir.

Yoğun kullanımda bir örneği yok, ya da ben bulamadım. Son on senede yayımlanmış, bu kelimeyi kullanan Türkçe bir kitabım da yok. Olan varsa aynı kullanımı devam ettimek bence makul olacaktır - sonuçta dil uzmanı değiliz. Görüşlerinizi bekliyorum.

İlgili commit: https://github.com/nodejs/iojs-tr/commit/1df64a9d8a4fa1c60e3480321522786c0471b24c#diff-2ec62d63140098846e77a981a6ca0291R39

**Comment by KiPSOFT-zz** [comment]
Bende sizinle aynı fikirdeyim lakin Compile şuan kullanılan yapıda çok kullanılan bir söz değil o yüzden Build kelimesine derleme olarak kullanmak daha mantıklı ama tabi bu iki kelimeye genel bir anlam bulacaksan o zaman iki farklı anlamda ki bu iki kelimeye aynı anlamı atamak sorunlu olacaktır. İnşa, Derleme bence seçilmesi gereken iki söz. Aslında inşa kelimesi bu iş için bire bir karşılık fakat biz günlük hayatımızda inşa kelimesini bir bina inşa etmek dışında başka bir anlamda kullanmıyoruz malesef.

Birkaç kaynak;
http://gnu-tr.sourceforge.net/sozluk.php - Kurgu(lamak)

**Comment by 0zguner** [comment]
Bence build hiçbir zaman derlemek olarak çevrilemez. Kurmak kelimesi de aslında güzel bir karşılık olabilir ama genelde kurmak windows ortamına özgü bir olay. Unix ve benzerlerinde inşa karşılığı tamamen doğru gibi geliyor bana. Ayrıca genel olarak C/C++ projelerinde build işlemi compile işlemini de içeriyor. Yani genelde Make build işlemi için kullanıldığından dolayı.

**Comment by KiPSOFT-zz** [comment]
Aslında betik dillerde Compile kelimesinin kullanımı neredeyse yok denecek kadar az.

**Comment by 0zguner** [comment]
Evet doğru. Ancak Node ve io.Js c/c++ gibi derlenmesi gereken yapılar içeriyor. Siz io.js i ve node u nasıl kuruyorsunuz bilmiyorum ama ben compile ederek kuruyorum. Ve build işlemini tamamen gerçekleştiriyorum.
