### ISSUE TITLE
Anasayfa güncellemesi

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#98]
[nodejs/io.js#369](https://github.com/nodejs/iojs.org/issues/369#issuecomment-117533682)

**Comment by KiPSOFT-zz** [comment]
@ayhankuru sen bu sayfayı düzenledin mi?

**Comment by c0b41** [comment]
#97 ve  anasayfayı güncelledim, burdan onay verirseniz merge edilcek https://github.com/nodejs/iojs.org/pull/393
