### ISSUE TITLE
Çevrilmesi Gereken Sayfalar

### ISSUE THREAD

**Issue by c0b41** [iojs/iojs-tr#99]
websitesinde bulunan governance.md  ve working-groups.md çevrilmesi gerekiyor

**Comment by c0b41** [comment]
çevrilmesi gereken sayfalar;
https://github.com/nodejs/iojs.org/blob/master/content/tr/governance.md
https://github.com/nodejs/iojs.org/blob/master/content/tr/working-groups.md
içerik çok fazla olduğu için yine bölerek çevirmek şart sanırım

**Comment by KiPSOFT-zz** [comment]
governance.md'ye bakarım ama biraz zaman lazım.

**Comment by c0b41** [comment]
@KiPSOFT zaman önemli değil
